#!/usr/bin/env bash
# A bash script that configures a new Ubuntu machine to install Nginx and listens on port 80

#This script stops if any command exits with a non-zero status
set -e

sudo apt-get update -y
sudo apt-get install nginx -y

sudo service nginx start
sudo ufw allow 'OpenSSH'
sudo ufw allow 'Nginx HTTP'

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx reload
