#!/usr/bin/env bash
# A bash script that configures a new Ubuntu machine to install Nginx and listens on port 80

#This script stops if any command exits with a non-zero status
set -e

sudo apt-get update -y
sudo apt-get install -y nginx

# sudo service nginx start
# sudo ufw allow 'OpenSSH'
# sudo ufw allow 'Nginx HTTP'

# cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo echo "<html><head><meta http-equiv=\"refresh\" content=\"0; url=https://github.com/JuggernautTej></head><body></body></html>" | sudo tee /var/www/html/redirect_me.html

sudo sed -i '/listen 80 default_server/a return 301 https://github.com/JuggernautTej;' etc/nginx/sites-available/default

sudo service nginx restart
