#!/usr/bin/env bash
# A bash script that configures a Nginx server

#This script stops if any command exits with a non-zero status
set -e

sudo apt-get update -y
sudo apt-get install -y nginx

sudo service nginx start

sudo sed -i "/http {/a\        add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html

sudo nginx -t
sudo service nginx restart
