#!/usr/bin/env bash
# A bash script that configures HAproxy on the lb-01 server

#HAProxy install
sudo apt-get update -y
sudo apt-get install -y haproxy

#HAProxy configuration
config_server="
frontend tiwatej.tech-frontend
	 bind *:80
	 mode http
  	 default_backend tiwatej.tech-backend

backend tiwatej.tech-backend
	balance roundrobin
	server 430047-web-01 54.146.61.253:80 check
	server 430047-web-02 54.82.27.122:80 check"
echo "$config_server" | sudo tee -a /etc/haproxy/haproxy.cfg

#Init script enables the HAProxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
